// @flow

import Realm from 'realm';
import {
  ChoiceItem,
  ChoiceItemPrice,
  DietaryOption,
  DishType,
  DocumentTemplate,
  Language,
  Menu,
  MenuItem,
  MenuItemPrice,
  MultiLanguagesString,
  Phone,
  Printer,
  Restaurant,
  RestaurantConfigurations,
  RestaurantImages,
  RestaurantLanguages,
  Rules,
  ServingTime,
  SortOrderIndex,
  Size,
  Table,
  TableState,
  Tag,
} from './schema';

export {
  ChoiceItemService,
  ChoiceItemPriceService,
  DietaryOptionService,
  DishTypeService,
  LanguageService,
  MenuService,
  MenuItemService,
  MenuItemPriceService,
  RestaurantService,
  ServingTimeService,
  SizeService,
  TableService,
  TableStateService,
  TagService,
} from './services';

export const realm = new Realm({
  schema: [
    ChoiceItem.getSchema(),
    ChoiceItemPrice.getSchema(),
    DietaryOption.getSchema(),
    DishType.getSchema(),
    DocumentTemplate.getSchema(),
    Language.getSchema(),
    Menu.getSchema(),
    MenuItem.getSchema(),
    MenuItemPrice.getSchema(),
    MultiLanguagesString.getSchema(),
    Phone.getSchema(),
    Printer.getSchema(),
    Restaurant.getSchema(),
    RestaurantConfigurations.getSchema(),
    RestaurantImages.getSchema(),
    RestaurantLanguages.getSchema(),
    Rules.getSchema(),
    ServingTime.getSchema(),
    SortOrderIndex.getSchema(),
    Size.getSchema(),
    TableState.getSchema(),
    Table.getSchema(),
    Tag.getSchema(),
  ],
  deleteRealmIfMigrationNeeded: true,
});
