// @flow

export default {
  ORDERS_MENU_SET_ORDER: 'ORDERS_MENU_SET_ORDER',
  ORDERS_MENU_ADD_MENU_ITEM_PRICE: 'ORDERS_MENU_ADD_MENU_ITEM_PRICE',
  ORDERS_MENU_REMOVE_MENU_ITEM_PRICE: 'ORDERS_MENU_REMOVE_MENU_ITEM_PRICE',
  ORDERS_MENU_UPDATE_MENU_ITEM_PRICE: 'ORDERS_MENU_UPDATE_MENU_ITEM_PRICE',
  ORDERS_MENU_CHANGE_NOTES: 'ORDERS_MENU_CHANGE_NOTES',
};
