// @flow

export default {
  DAILY_REPORT_FROM_DATETIME_CHANGED: 'DAILY_REPORT_FROM_DATETIME_CHANGED',
  DAILY_REPORT_TO_DATETIME_CHANGED: 'DAILY_REPORT_TO_DATETIME_CHANGED',
  DAILY_REPORT_DATETIME_RANGE_CHANGED: 'DAILY_REPORT_DATETIME_RANGE_CHANGED',
};
